#include "mrb_fltk3.h"
#include <fltk3/enumerations.h>

/*********************************************************
 * FLTK3 constants
 *********************************************************/
#define DEFINE_INT_CONST(x) \
  mrb_define_const(mrb, _class_fltk3, # x, mrb_fixnum_value((mrb_int) fltk3::x));

void
mrb_fltk3_constants_init(mrb_state* mrb, struct RClass* _class_fltk3)
{
  /* events */
  DEFINE_INT_CONST(NO_EVENT);
  DEFINE_INT_CONST(PUSH);
  DEFINE_INT_CONST(RELEASE);
  DEFINE_INT_CONST(ENTER);
  DEFINE_INT_CONST(LEAVE);
  DEFINE_INT_CONST(DRAG);
  DEFINE_INT_CONST(FOCUS);
  DEFINE_INT_CONST(UNFOCUS);
  DEFINE_INT_CONST(KEYDOWN);
  DEFINE_INT_CONST(KEYBOARD);
  DEFINE_INT_CONST(KEYUP);
  DEFINE_INT_CONST(CLOSE);
  DEFINE_INT_CONST(MOVE);
  DEFINE_INT_CONST(SHORTCUT);
  DEFINE_INT_CONST(DEACTIVATE);
  DEFINE_INT_CONST(ACTIVATE);
  DEFINE_INT_CONST(HIDE);
  DEFINE_INT_CONST(SHOW);
  DEFINE_INT_CONST(PASTE);
  DEFINE_INT_CONST(SELECTIONCLEAR);
  DEFINE_INT_CONST(MOUSEWHEEL);
  DEFINE_INT_CONST(DND_ENTER);
  DEFINE_INT_CONST(DND_DRAG);
  DEFINE_INT_CONST(DND_LEAVE);
  DEFINE_INT_CONST(DND_RELEASE);

  /* when */
  DEFINE_INT_CONST(WHEN_NEVER);
  DEFINE_INT_CONST(WHEN_CHANGED);
  DEFINE_INT_CONST(WHEN_NOT_CHANGED);
  DEFINE_INT_CONST(WHEN_RELEASE);
  DEFINE_INT_CONST(WHEN_RELEASE_ALWAYS);
  DEFINE_INT_CONST(WHEN_ENTER_KEY);
  DEFINE_INT_CONST(WHEN_ENTER_KEY_ALWAYS);
  DEFINE_INT_CONST(WHEN_ENTER_KEY_CHANGED);

  /* keys */
  DEFINE_INT_CONST(BackSpaceKey);
  DEFINE_INT_CONST(TabKey);
  DEFINE_INT_CONST(EnterKey);
  DEFINE_INT_CONST(PauseKey);
  DEFINE_INT_CONST(ScrollLockKey);
  DEFINE_INT_CONST(EscapeKey);
  DEFINE_INT_CONST(HomeKey);
  DEFINE_INT_CONST(LeftKey);
  DEFINE_INT_CONST(UpKey);
  DEFINE_INT_CONST(RightKey);
  DEFINE_INT_CONST(DownKey);
  DEFINE_INT_CONST(PageUpKey);
  DEFINE_INT_CONST(PageDownKey);
  DEFINE_INT_CONST(EndKey);
  DEFINE_INT_CONST(PrintKey);
  DEFINE_INT_CONST(InsertKey);
  DEFINE_INT_CONST(MenuKey);
  DEFINE_INT_CONST(HelpKey);
  DEFINE_INT_CONST(NumLockKey);
  DEFINE_INT_CONST(KPKey);
  DEFINE_INT_CONST(KPEnterKey);
  DEFINE_INT_CONST(KPLastKey);
  DEFINE_INT_CONST(FKey);
  DEFINE_INT_CONST(FLastKey);
  DEFINE_INT_CONST(ShiftLKey);
  DEFINE_INT_CONST(ShiftRKey);
  DEFINE_INT_CONST(ControlLKey);
  DEFINE_INT_CONST(ControlRKey);
  DEFINE_INT_CONST(CapsLockKey);
  DEFINE_INT_CONST(MetaLKey);
  DEFINE_INT_CONST(MetaRKey);
  DEFINE_INT_CONST(AltLKey);
  DEFINE_INT_CONST(AltRKey);
  DEFINE_INT_CONST(DeleteKey);

  /* mouse buttons and modifiers */
  DEFINE_INT_CONST(LEFT_MOUSE);
  DEFINE_INT_CONST(MIDDLE_MOUSE);
  DEFINE_INT_CONST(RIGHT_MOUSE);
  DEFINE_INT_CONST(SHIFT);
  DEFINE_INT_CONST(CAPS_LOCK);
  DEFINE_INT_CONST(CTRL);
  DEFINE_INT_CONST(ALT);
  DEFINE_INT_CONST(NUM_LOCK);
  DEFINE_INT_CONST(META);
  DEFINE_INT_CONST(SCROLL_LOCK);
  DEFINE_INT_CONST(BUTTON1);
  DEFINE_INT_CONST(BUTTON2);
  DEFINE_INT_CONST(BUTTON3);
  DEFINE_INT_CONST(BUTTONS);
  DEFINE_INT_CONST(KEY_MASK);
  DEFINE_INT_CONST(COMMAND);
  DEFINE_INT_CONST(CONTROL);

  /* label types */
  DEFINE_INT_CONST(NORMAL_LABEL);
  DEFINE_INT_CONST(NO_LABEL);
  DEFINE_INT_CONST(SHADOW_LABEL);
  DEFINE_INT_CONST(ENGRAVED_LABEL);
  DEFINE_INT_CONST(EMBOSSED_LABEL);

  /* alignment */
  DEFINE_INT_CONST(ALIGN_CENTER);
  DEFINE_INT_CONST(ALIGN_TOP);
  DEFINE_INT_CONST(ALIGN_BOTTOM);
  DEFINE_INT_CONST(ALIGN_LEFT);
  DEFINE_INT_CONST(ALIGN_RIGHT);
  DEFINE_INT_CONST(ALIGN_INSIDE);
  DEFINE_INT_CONST(ALIGN_TEXT_OVER_IMAGE);
  DEFINE_INT_CONST(ALIGN_IMAGE_OVER_TEXT);
  DEFINE_INT_CONST(ALIGN_CLIP);
  DEFINE_INT_CONST(ALIGN_WRAP);
  DEFINE_INT_CONST(ALIGN_IMAGE_NEXT_TO_TEXT);
  DEFINE_INT_CONST(ALIGN_TEXT_NEXT_TO_IMAGE);
  DEFINE_INT_CONST(ALIGN_IMAGE_BACKDROP);
  DEFINE_INT_CONST(ALIGN_TOP_LEFT);
  DEFINE_INT_CONST(ALIGN_TOP_RIGHT);
  DEFINE_INT_CONST(ALIGN_BOTTOM_LEFT);
  DEFINE_INT_CONST(ALIGN_BOTTOM_RIGHT);
  DEFINE_INT_CONST(ALIGN_LEFT_TOP);
  DEFINE_INT_CONST(ALIGN_RIGHT_TOP);
  DEFINE_INT_CONST(ALIGN_LEFT_BOTTOM);
  DEFINE_INT_CONST(ALIGN_RIGHT_BOTTOM);
  DEFINE_INT_CONST(ALIGN_NOWRAP);

  /* fonts */
  DEFINE_INT_CONST(HELVETICA);
  DEFINE_INT_CONST(HELVETICA_BOLD);
  DEFINE_INT_CONST(HELVETICA_ITALIC);
  DEFINE_INT_CONST(HELVETICA_BOLD_ITALIC);
  DEFINE_INT_CONST(COURIER);
  DEFINE_INT_CONST(COURIER_BOLD);
  DEFINE_INT_CONST(COURIER_ITALIC);
  DEFINE_INT_CONST(COURIER_BOLD_ITALIC);
  DEFINE_INT_CONST(TIMES);
  DEFINE_INT_CONST(TIMES_BOLD);
  DEFINE_INT_CONST(TIMES_ITALIC);
  DEFINE_INT_CONST(TIMES_BOLD_ITALIC);
  DEFINE_INT_CONST(SYMBOL);
  DEFINE_INT_CONST(SCREEN);
  DEFINE_INT_CONST(SCREEN_BOLD);
  DEFINE_INT_CONST(ZAPF_DINGBATS);
  DEFINE_INT_CONST(FREE_FONT);
  DEFINE_INT_CONST(BOLD);
  DEFINE_INT_CONST(ITALIC);
  DEFINE_INT_CONST(BOLD_ITALIC);

  /* colors */
  DEFINE_INT_CONST(FOREGROUND_COLOR);
  DEFINE_INT_CONST(BACKGROUND2_COLOR);
  DEFINE_INT_CONST(INACTIVE_COLOR);
  DEFINE_INT_CONST(SELECTION_COLOR);
  DEFINE_INT_CONST(GRAY0);
  DEFINE_INT_CONST(DARK3);
  DEFINE_INT_CONST(DARK2);
  DEFINE_INT_CONST(DARK1);
  DEFINE_INT_CONST(BACKGROUND_COLOR);
  DEFINE_INT_CONST(LIGHT1);
  DEFINE_INT_CONST(LIGHT2);
  DEFINE_INT_CONST(LIGHT3);
  DEFINE_INT_CONST(BLACK);
  DEFINE_INT_CONST(RED);
  DEFINE_INT_CONST(GREEN);
  DEFINE_INT_CONST(YELLOW);
  DEFINE_INT_CONST(BLUE);
  DEFINE_INT_CONST(MAGENTA);
  DEFINE_INT_CONST(CYAN);
  DEFINE_INT_CONST(DARK_RED);
  DEFINE_INT_CONST(DARK_GREEN);
  DEFINE_INT_CONST(DARK_YELLOW);
  DEFINE_INT_CONST(DARK_BLUE);
  DEFINE_INT_CONST(DARK_MAGENTA);
  DEFINE_INT_CONST(DARK_CYAN);
  DEFINE_INT_CONST(WHITE);
  DEFINE_INT_CONST(FREE_COLOR);
  DEFINE_INT_CONST(NUM_FREE_COLOR);
  DEFINE_INT_CONST(GRAY_RAMP);
  DEFINE_INT_CONST(NUM_GRAY);
  DEFINE_INT_CONST(GRAY);
  DEFINE_INT_CONST(COLOR_CUBE);

  /* damage */
  DEFINE_INT_CONST(DAMAGE_CHILD);
  DEFINE_INT_CONST(DAMAGE_EXPOSE);
  DEFINE_INT_CONST(DAMAGE_SCROLL);
  DEFINE_INT_CONST(DAMAGE_OVERLAY);
  DEFINE_INT_CONST(DAMAGE_USER1);
  DEFINE_INT_CONST(DAMAGE_USER2);
  DEFINE_INT_CONST(DAMAGE_ALL);
}

/* vim:set et ts=2 sts=2 sw=2 tw=0: */
